export { defaultFailureConfig, DEFAULT_STRESS_WEIGHTS } from './config'
export type { FailureConfig } from './config'
export { stressVector, entropy, entropyFromConfig } from './stress'
export { lambdaEntropy, lambdaAge, lambdaD, pFail } from './hazard'
export { tickCharger, getChargerPFail } from './tickCharger'
export { runMonteCarloDiagnostics } from './diagnostics'
export type { DiagnosticsResult } from './diagnostics'
